services:
  _defaults:
    autowire: true
    autoconfigure: true
    public: false

  Auxmoney\OpentracingGuzzleBundle\Middleware\GuzzleTracingHeaderInjection: ~
  Auxmoney\OpentracingGuzzleBundle\Middleware\GuzzleRequestSpanning: ~
